---
# 1. Positive extensions for interesting files
level-one_exts:
  - xmi
  - uml

# 2. Extensions marked as positive only if file-name contains a keyword (See 3.)
level-two_exts:
  - jpg
  - jpg
  - gif
  - bmp
  - png
  - tiff
  - emf
  - exif
  - wmf

# 3. Keywords
keywords:
  - uml
  - class-diagram
  - classdiagram
  - cd
  - class_diagram
  - class+diagram